package com.ddlabs.atlassian.metrics.model;
import net.java.ao.Entity;

public interface MSConfig extends Entity {
    void setServerName(String serverName);
    void setDescription(String description);
    void setServerType(String serverType);
    void setDomain(String domain);
    void setClientSecret(String clientSecret);
    void setClientId(String clientId);
    void setSite(String site);
    void setOrgName (String orgName);
    void setOrgId (String orgId);
    void setRedirectUrl(String redirectUrl);
    void setCodeVerifier(String codeVerifier);
    void setCodeChallenge(String codeChallenge);
    void setAccessToken(String accessToken);
    void setRefreshToken(String refreshToken);
    void setAccessTokenExpiry(Long accessTokenExpiry);
    void setTokenType(String tokenType);
    void setScope(String scope);
    void setCodeCreationTime(Long codeCreationTime);
    void setCodeExpirationTime(Long codeExpirationTime);
    void setEnabled(Boolean enabled);
    void setConfigured(Boolean configured);
    void setApiEndpoint(String apiEndpoint);
    void setOauthEndpoint(String oauthEndpoint);
    void setTokenEndpoint(String tokenEndpoint);
    String getServerName();
    String getDescription();
    String getServerType();
    String getDomain();
    String getClientSecret();
    String getClientId();
    String getSite ();
    String getOrgName();
    String getOrgId ();
    String getRedirectUrl();
    String getCodeVerifier();
    String getCodeChallenge();
    String getAccessToken();
    String getRefreshToken();
    Long getAccessTokenExpiry();
    String getTokenType();
    Long getCodeCreationTime();
    Long getCodeExpirationTime();
    Boolean getEnabled();
    Boolean getConfigured();
    String getApiEndpoint();
    String getOauthEndpoint();
    String getTokenEndpoint();
    String getScope();
}
